hdbt_admin_tools.site_settings:
  type: config_object
  label: 'Site settings'
  mapping:
    site_settings:
      label: 'Site settings'
      type: mapping
      mapping:
        default_icon:
          label: 'Default icon'
          type: label
        theme_color:
          label: 'Theme color'
          type: label
        koro:
          label: 'Koro'
          type: label
    footer_settings:
      label: 'Footer settings'
      type: mapping
      mapping:
        footer_color:
          label: 'Footer color'
          type: label
        footer_top_title:
          label: 'Footer top title'
          type: label
        footer_top_content:
          label: 'Footer top content'
          type: text_format

hdbt_admin_tools.cookie_consent_intro:
  type: config_object
  label: 'Cookie consent intro'
  mapping:
    cc:
      label: 'Cookie consent'
      type: mapping
      mapping:
        title:
          label: 'Cookie consent intro title'
          type: label
        content:
          label: 'Cookie consent intro content'
          type: text_format
